import type { Metadata } from "next";
import '@coinbase/onchainkit/styles.css';
import { Inter, Source_Code_Pro } from "next/font/google";
import { RootProvider } from "./rootProvider";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header"; // <--- 1. Import Header

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const sourceCodePro = Source_Code_Pro({ variable: "--font-source-code-pro", subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description: "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <RootProvider>
          {/* 2. HEADER: Now it stays at the top of EVERY page */}
          <Header />

          {/* 3. MAIN CONTENT: Padded top/bottom so it doesn't hide behind Header or Nav */}
          <main style={{ paddingBottom: '80px', paddingTop: '20px', minHeight: '100vh' }}>
            {children}
          </main>

          <BottomNav />
        </RootProvider>
      </body>
    </html>
  );
}
